name: Continuous Integration
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1.3.0
        with:
          node-versions: 12.x
      - name: Install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
