name: Continuous Delivery
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 12.x
      - name: Get NPM cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Cache NPM
        uses: actions/cache@v1.1.0
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Setup Node.js 12.x
      uses: actions/setup-node@v1.4.4
      with:
        node-version: 12.x
    - name: Get NPM cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - name: Cache NPM
      uses: actions/cache@v1.1.0
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: npm ci
    - name: Build product
      run: npm run build
    - name: Upload build artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: dist
        path: /home/runner/work/simple-roulette/dist
  e2e:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Setup Node.js 12.x
      uses: actions/setup-node@v1.4.4
      with:
        node-version: 12.x
    - name: Get NPM cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - name: Cache NPM
      uses: actions/cache@v1.1.0
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: npm ci
    - name: Donwload build artifact
      uses: actions/download@v2.0.0
      with:
        name: dist
        path: /home/runner/work/simple-roulette
    - name: Build test environment
      run: docker-compose up -d
    - name: e2e
      run: npm run cypress:run
    - name: Upload error screenshots
      if: ${{ failure() }}
      uses: actions/upload-artifact@v1.0.0
      with:
        name: screenshots
        path: /home/runner/work/simple-roulette/simple-roulette/cypress/screenshots
    - name: Upload videos
      if: ${{ always() }}
      uses: actions/upload-artifact@v1.0.0
      with:
        name: videos
        path: /home/runner/work/simple-roulette/simple-roulette/cypress/videos
  deploy:
    needs: e2e
    # if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: Donwload build artifact
      uses: actions/download@v2.0.0
      with:
        name: dist
        path: /home/runner/work/simple-roulette
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.7.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
