name: Continuous Integration
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1.3.0
        with:
          node-versions: 12.x
      - name: Get NPM cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Cache NPM
        uses: actions/cache@v1.1.0
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
  e2e:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Setup Node.js 12.x
      uses: actions/setup-node@v1.3.0
      with:
        node-versions: 12.x
    - name: Get NPM cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - name: Cache NPM
      uses: actions/cache@v1.1.0
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: npm ci
    - name: Build test environment
      run: docker-compose up -d
    - name: e2e
      run: npm run cypress:run
    - name: Upload error screenshots
      uses: actions/upload-artifact@v1.0.0
      with:
        name: screenshots
        path: /home/runner/work/simple-roulette/simple-roulette/cypress/screenshots
    - name: Upload error videos
      uses: actions/upload-artifact@v1.0.0
      with:
        name: videos
        path: /home/runner/work/simple-roulette/simple-roulette/cypress/videos
